name: 
description: 
author: 
inputs:
  singularity-version:
    description: Version of singularity to setup
    required: false
    default: 3.6.1
  singularity-file:
    description: singularity file to setup
    required: false
    default: Singularity
  singularity-name:
    description: singularity image name
    required: false
    default: ${{ github.repository }}
  action-command:
    description: Set the command for docker running the singularity contianer
    required: true
    default: build
  test-command:
    description: Used to test contianer is normal
    required: false
    default: echo hello
  TOKEN:
    description: The token used to push github package
    required: false

runs:
  using: "composite"
  steps:    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.TOKEN }}
    - uses: 'docker://ghcr.io/ifurther/actions:latest'
      with:
        args:
          - ${{inputs.action-command}}
          - ${{inputs.singularity-file}}
        - ${{inputs.singularity-name}}.sif
branding:
  icon: 'aperture' 
  color: 'green'
