name: 
description: 
author: 
inputs:
  singularity-version:
    description: Version of singularity to setup
    required: false
    default: 3.6.1
  singularity-file:
    description: singularity file to setup
    required: false
    default: Singularity
  singularity-name:
    description: singularity image name
    required: false
    default: ${{ github.repository }}
  token:
    description: Used to pull singularity distributions from eWaterCycle/singularity-versions. Since there's a default, this is typically not supplied by the user.
    required: false
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/build-push-action@v2
      with:
        context: ./build
        push: false
        tags: user/app:latest
        build-args:  |
           SINGULARITY_RECIPE=${{inputs.singularity-file}}
           SINGULARITY_IMAGE=${{inputs.singularity-name}}
branding:
  icon: 'aperture' 
  color: 'green'
