name: build-test

on:
  push:
    branches:
      - master


jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./build
        push: false
        tags: user/app:latest
